{% set name = "kio" %}
{% set version = "5.72.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kio-{{ version }}.tar.xz
  sha256: 0ab32bff63f542598e95be64a793eefe8f51b041fbb447256a4aa1c756214ba2

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kio', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('libudev') }}  # [linux]
    - {{ cdt('libudev-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - krb5
    - kauth >={{ major_minor }}
    - ki18n >={{ major_minor }}
    - karchive >={{ major_minor }}
    - kconfig >={{ major_minor }}
    - kcodecs >={{ major_minor }}
    - kxmlgui >={{ major_minor }}
    - kservice >={{ major_minor }}
    - kitemviews >={{ major_minor }}
    - kcompletion >={{ major_minor }}
    - kcoreaddons >={{ major_minor }}
    - kiconthemes >={{ major_minor }}
    - kcrash >={{ major_minor }}
    - solid >={{ major_minor }}
    - kwallet >={{ major_minor }}
    - kbookmarks >={{ major_minor }}
    - kdbusaddons >={{ major_minor }}
    - kjobwidgets >={{ major_minor }}
    - kcompletion >={{ major_minor }}
    - ktextwidgets >={{ major_minor }}
    - kwindowsystem >={{ major_minor }}
    - kwidgetsaddons >={{ major_minor }}
    - kconfigwidgets >={{ major_minor }}
    - knotifications >={{ major_minor }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5KIOCore.so

about:
  home: https://api.kde.org/frameworks/kio/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Network transparent access to files and data
  description: |
    This framework implements almost all the file management functions you will ever need.
    In fact, the KDE file manager (Dolphin) and the KDE file dialog also uses this to
    provide its network-enabled file management.

    It supports accessing files locally as well as via HTTP and FTP out of the box and
    can be extended by plugins to support other protocols as well. There is a variety
    of plugins available, e.g. to support access via SSH.

    The framework can also be used to bridge a native protocol to a
    file-based interface. This makes the data accessible in all applications
    using the KDE file dialog or any other KIO enabled infrastructure.
  dev_url: https://cgit.kde.org/kio.git/tree

extra:
  recipe-maintainers:
    - scopatz
