travis:
  secure:
    BINSTAR_TOKEN: Pzcwkw1QF17fy6kUpVTILe5BgezrgDd+BjswOUb3OqecBUEztIguyrS4MjEjUBfwzs99k6r4XqbumdxYni9L98tn7zgu6ooZRzTBQCF9BFsckB4QS9cDJ3ImWHE0v3D72oqsn9kxFLO4wmfedrb/RAwZFC4hhUqoi5zPTy6JDfMCcQzL8V4eQsafBbMzoCQszELNHmKkN2VEPSKKozfd4y01tWmHlmxHehzdUFpC8tO7sQHjhQ/koS8qcm6DlxeJ1f5foPe29dYoSEHFKn+pSiyg+ckDDLRWL4TjJDHO4kUQDqN26Mxo0oHQbkJ0IeUXD6m8ielcPIW0qj8+hZF6tX7XyLYgVQR8N+Der2wfOpmvoTFAU1Z0rdBteI/B7cufGToP1EE1uis6TQxwerzamGrvmqraS6QymmyZjcDuBt9U7h+NNZHAm9QQSyTSWsJ1JHZCmsokmffF2sC/kCdNNCiLQwT0wzkpegyFAv77JGr/CaTpnGdr+0TKm0eIXUJbhn8v6pADAr8IwRZSCFQF0U3e9J6506MisesHCiAHCnBw4WXXnBt24cQYpn624jOyz2dBKRQVGSI33XHMYp2G63oM5S3duJRTJ5C3b5UdMEmYStwH5PVW03n4Ux9EllW6Ugkkm3bpXy8LRsdtnwkv2GhUU67Ep8pdDkc+3z21u3w=
conda_forge_output_validation: true
bot:
  check_solvable: True
  
